### ISSUE TITLE
How to run Minecraft 0.30c in multi-player mode.

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/minecraft-classic-protocol#2]
No way to test without that

**Comment by rom1504** [comment]
Alright, found a solution, use [classicube](https://www.classicube.net/) you need to install [mono](http://www.mono-project.com/) first. It works well :smile: with no errors.

**Comment by rom1504** [comment]
it works pretty well :) 
No errors.
Trying to make it spawn now.

**Comment by rom1504** [comment]
ok

**Comment by rom1504** [comment]
ah we might want to get the vanilla client to run in multiplayer mode now

**Comment by rom1504** [comment]
classicube works

**Comment by ghost** [comment]
I've planned to write a hacky way to run the original minecraft classic multiplayer applet, maybe I'll try it out.
