### ISSUE TITLE
chunk map packet

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/minecraft-classic-protocol#4]
is weird

https://github.com/UnknownShadow200/ClassicalSharp/blob/eb3bbc168a86caaa9cf5bb61f8bc6854a7d17a28/ClassicalSharp/Network/NetworkProcessor.Original.cs#L120

http://wiki.vg/Classic_Protocol#Server_.E2.86.92_Client_packets

I don't quite understand yet what's the size sent to us.

is it the size of the compressed chunk or uncompressed ?

**Comment by rom1504** [comment]
need to handle that to spawn a player

**Comment by ghost** [comment]
It is compressed in the way that the actual level.dat is as far as I understand. Here is a library I wrote for reading them (writing isn't supported yet, but I could do it easily). https://github.com/mhsjlw/minecraft-classic-anvil exact code: https://github.com/mhsjlw/minecraft-classic-anvil/blob/master/src/read.js

**Comment by ghost** [comment]
Here is an example `level.dat` for testing too, https://github.com/mhsjlw/minecraft-classic-anvil/blob/master/examples/level.dat

**Comment by rom1504** [comment]
"Contains a chunk of gzipped map (not level.dat file)."

**Comment by rom1504** [comment]
but the pb I'm having now is how to decompress the chunk, I'll figure out how to read/write it afterwards

**Comment by ghost** [comment]
I'm aware that's it's a chunk not the entire file, but minecraft-classic-anvil allows you to get chunks. And the individual chunks are gzipped, so just gunzip it, then you've got the chunk.

**Comment by rom1504** [comment]
"so just gunzip it" : yes, but gunzip _what_, that's the problem. the protocol is not telling us the compressed length.
I need to read this more carefully, but I think the answer is in the gzip headers https://github.com/UnknownShadow200/ClassicalSharp/blob/eb3bbc168a86caaa9cf5bb61f8bc6854a7d17a28/ClassicalSharp/Network/NetworkProcessor.Original.cs#L120

**Comment by rom1504** [comment]
https://github.com/MineLib/MineLib.Network/blob/master/Classic/Packets/Server/LevelDataChunk.cs#L17 : seems like it's always 1024

**Comment by rom1504** [comment]
Except I can't zlib.gunzipSync it

It does look like a gzip'd buffer though : 

1f8b0800000000000000ec5d5b92eb280cc5dfa9ea6417c93266ffab9a8e6dde929084c0765f9f9ab91ddb20740488a7b1fbcfb9c78d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb871e3c68d1b376edcb8f18be5c6dfc4ebf53a5a851b37e6c2b9a335380a6ea5feaff277ee6ff1f77c24e1c5914e0bb7431861f923fc9d131ac0a518aada50ecbac7b22ce57fe90210b22fb8322e195746bd0c5275ab322ce57f49fa41e1ba0a8bf8cb629c04187f45f9f73fc6286a83723c5694f5c200fcccbc48b657e3d18c6a650001abab18a0b84e9982e00a16053e0e08ffd5027019e0e222fc71032c75255884fd7f3b3d07a19e8f2a723a2b0932d9214296c8b96c02ccc7c1c55d4eff790c7f999a6cfe62c59f4f6f806dd2f394539f995245b7078c003c4242fef2f7267b7dd371eef54ded6cc53ff26765763ea1c1ed12be02ffd12e5122fef57ac96b665600423f8991d25e9f465602998f2ee9f39348e9b3525d13dae80fe62f08bdd30feb6dfbbff4ea5bca3fed24f0d31468380e2be9f5bfc7fe7337436bf5116a1364fccf60806abd95bff80a9195553ab1b6f628169b1fe99dc1499f813fbcdeee4d21c0053af81022ebfc974406d647faedf550b124490c4396e7b9ff63a2ea1dfff01a9fb3f11738be1415fb5fc80748472163ab737c25d39f9ff3ce77546a1574adfc3e83ff93f60e6300f32f6e0c49a8c251fc73bd92667f3222ff89bd002cff276fb3cbb498d80dac4be5845e1ea8477231903fa3777e0cfd59f93fb915624c7e2c75291c3b0d30507891126bf26376dfc04fdd83cf2c9361f1df83daa5cb444c32ede1fd29feb5d024ebc36295aa8bcf499d4fdf34dd548152bc9f915b629dd30d7198e9c3eccbbb83721f101b56ed027f60a6633426793b288d3de963f91f38ce4ff92f75f93fead59221fd1dacee39573cfab3fcb11a101f84842fce1ff6757809f00fd2840fe4df03bc9575d88eac10235f6fb9327ddca3c22b325b9c49eb4d03dd3da79309f0f73133fe838cc1ee067608d788df4a4072634069085dd0c106d0474daeedf967e20759a0436c3df539d61b18

**Comment by deathcap** [comment]
@rom1504 when I try to uncompress that buffer with `gunzip` I get "unexpected end of file" (decompresses to: ^@@^@^@^K^K..., 65536 bytes), truncated?

**Comment by rom1504** [comment]
I'm getting the same error yeah.
Trying to figure out what's wrong.

**Comment by rom1504** [comment]
(the code currently in the repo isn't up to date)

**Comment by rom1504** [comment]
I wonder whether the classic server jar I got is correct. anybody got that jar somewhere ?

@mhsjlw where did you got the jar you gave me ?

**Comment by rom1504** [comment]
Well ClassicCube is able to connect to it so I guess we should be able to too.

**Comment by rom1504** [comment]
> 21:52 < Hetal> Minecraft Classic Original Server jars won't work with ClassiCube
> 21:52 < Hetal> http://www.classicube.net/server/host/

**Comment by rom1504** [comment]
Ah I think I get it. You're supposed to uncompress the whole thing at once when you got all the chunk packets.

**Comment by rom1504** [comment]
https://github.com/OpenClassic/OpenClassic/blob/master/src/main/java/org/spacehq/openclassic/client/network/handler/LevelFinalizeMessageHandler.java

https://github.com/OpenClassic/OpenClassic/blob/master/src/main/java/org/spacehq/openclassic/client/network/handler/LevelDataMessageHandler.java

What a weird thing.

**Comment by rom1504** [comment]
made decoding work in fdc84119b515d0c375772e9042a70146c319eb23

**Comment by rom1504** [comment]
> After decompression the map consists of a big-endian int(4 bytes) containing the number of blocks, followed by a raw map array. (chunk is up to 1024 bytes, padded with 0x00s if less).

**Comment by rom1504** [comment]
now working !

Still need a classic-world class but can be done in an other issue.
