### ISSUE TITLE
classic extension plugin

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/minecraft-classic-protocol#5]
http://wiki.vg/Classic_Protocol_Extension

https://github.com/mhsjlw/minecraft-classic-protocol/commit/462fcca6eb677920efb354f85cb74ec4a71cda37 will help

I think the extension should be a separate repo, something like minecraft-classic-protocol-extension, which will be an optional plugin to minecraft-classic-protocol. so we keep a vanilla classic repo (like we are doing for forge with nmp)

a protocol_extension.json will probably have to be written

**Comment by rom1504** [comment]
One of the reason I think it's better in a separate repo is because the classic protocol (in addition to being vanilla) is not changing, and won't change.
While the extension is moving, and the thing that support it will have to keep being updated

http://wiki.vg/Classic_Protocol_Extension/History

**Comment by rom1504** [comment]
ongoing work at https://github.com/mhsjlw/minecraft-classic-protocol-extension

**Comment by ghost** [comment]
done
